### ISSUE TITLE
initial loading takes several minutes

### ISSUE THREAD

**Issue by ero24** [rih28/MBAndroidTest#1]
I feel like this issue is already known but just wanted to stick it here as well. On both phones when I downloaded the app it was taking ages to load all the questions. (I used the link directly from the phones' browsers in both cases)

**Comment by rih28** [comment]
Is this the black page with the percentage counter?

**Comment by ero24** [comment]
yes, it took a long time on both phones to reach 100%

**Comment by rih28** [comment]
I think I have fixed this. Will carry out a build and send one out when you have finished testing this version.

**Comment by ero24** [comment]
Checked on both phone and I timed in on the Nokia one (which is the more glitchy anyway) and it took 1min22sec to download 100% so definitely improved
