### ISSUE TITLE
The app crashed once with no reason on Sony 

### ISSUE THREAD

**Issue by yw666666** [rih28/MBAndroidTest#10]
Just for the record

**Comment by rih28** [comment]
Ok. This is worrying

**Comment by yw666666** [comment]
Happened again 
![06511274-7788-4b85-9ce2-02118ea736b4](https://user-images.githubusercontent.com/42607534/50129228-f76c1280-02b2-11e9-8b76-467861042ba8.jpeg)

**Comment by yw666666** [comment]
I think this is getting better
