### ISSUE TITLE
Stats Q10 hint2

### ISSUE THREAD

**Issue by yw666666** [rih28/MBAndroidTest#11]
Histogram question
Hint 2 last little question, the formula triangle, chose the first answer 
Are the bold and light fonts supposed to be the other way round?
![Uploading 58BDF663-078B-4305-88EC-3D05306307F9.jpeg…]()

**Comment by rih28** [comment]
I need to check this one as I cant see the image.

**Comment by yw666666** [comment]
This is the response to the first choice
![wechat image_20190110113054](https://user-images.githubusercontent.com/42607534/50944440-4af50900-14cb-11e9-8374-4e5d3d4d811d.jpg)

compare with the response to the second choice:
![wechat image_20190110113102](https://user-images.githubusercontent.com/42607534/50944462-619b6000-14cb-11e9-9acd-de69d989c5e6.jpg)
