### ISSUE TITLE
Going back to the topic page

### ISSUE THREAD

**Issue by yw666666** [rih28/MBAndroidTest#12]
On the question page, when I clicked on the arrow at the top left, it went to the last question instead of going back to the topic page. I’m 100% sure that I clicked on the arrow. This happened a few times on both phones. And among these there was one case in which the “last Q” button turned into a light color, as if I’m at the first question but I was not.

**Comment by rih28** [comment]
Has this mainly been resolved?

**Comment by yw666666** [comment]
The 'last Q' problem didn't happen again, but I found another problem:
when I clicked on the arrow, regardless of what topic I was doing, it went to this question:
(Again, this does not always happen, but it happened a few times in the newest version on Sony. I will update you with the other phone later.)
![wechat image_20190109135510](https://user-images.githubusercontent.com/42607534/50879542-399df500-1416-11e9-8c34-cd751402d9b9.jpg)
