### ISSUE TITLE
golden hints

### ISSUE THREAD

**Issue by yw666666** [rih28/MBAndroidTest#14]
When I pressed on the golden hint, nothing happened. Only after I released it the reviewed contents of the hint (in the question page) disappeared and then quickly reappeared. Should this happen before I release it instead? I don’t have my iPhone to cross check at the moment. And I don’t remember if we mentioned this during our video chat...?

**Comment by rih28** [comment]
Hmm, has this been resolved yet? The new version should not struggle with things like this.

**Comment by yw666666** [comment]
fixed
