### ISSUE TITLE
the app crashed on the third question in Probability

### ISSUE THREAD

**Issue by ero24** [rih28/MBAndroidTest#16]
this has happened before in an another question but never on the Samsung phone, always on the Nokia and always in the same way, the response to the answer to the little question seems to be stuck there flashing then I tapped elsewhere and it crashed
![img_0116](https://user-images.githubusercontent.com/42607536/50155149-2ee2bb00-02c3-11e9-99da-e0c60bfe78de.JPG)

**Comment by rih28** [comment]
This kind of thing should be resolved in the most part not.

**Comment by ero24** [comment]
hasn't happened in a while now, this week not at all
