### ISSUE TITLE
typo in Q1 Algebra, 4th hint, 3rd little question

### ISSUE THREAD

**Issue by ero24** [rih28/MBAndroidTest#2]
it says 'out' instead of 'our'
(i tried to take a screenshot on the android phone but obviously it didn't work so i figured it would be easier to just take a pic with my phone anyway)

![unknown](https://user-images.githubusercontent.com/42607536/50084636-8d3e6980-01ef-11e9-90d4-07d49e3305a2.jpeg)

**Comment by rih28** [comment]
I will give out a new build tonight.

**Comment by ero24** [comment]
it is now saying 'our' correctly
