### ISSUE TITLE
The new version only downloaded the first 5 questions for each section

### ISSUE THREAD

**Issue by yw666666** [rih28/MBAndroidTest#23]
Tried deleting and downloading for a few times. Sony downloaded 20 questions for the first time, but there was the black page issue (#22). Both phones downloaded only 5 quetsions after this. Both are connected to internet all the time.

**Comment by yw666666** [comment]
To make things clear this was the second version

**Comment by rih28** [comment]
Hopefully this version will work. Android does not seem to tolerate the methods applied to iPhone.

**Comment by yw666666** [comment]
yes this problem seems to be solved now!

**Comment by yw666666** [comment]
for this newest version Huawei downloaded only the first 5. I tried a few times but it didn't get any better. I will try again and update you later.
