### ISSUE TITLE
Algebra Q6, strange things happening

### ISSUE THREAD

**Issue by ero24** [rih28/MBAndroidTest#24]
I was clicking on the hints to check them and the first one was fine but I noticed that when I clicked on the second one and answered all the little questions it didn't make that button blue, instead it made the fifth hint blue... the hints continued to come up in order it was just really strange that the buttons at the bottom weren't following the order
![img_0125](https://user-images.githubusercontent.com/42607536/50226625-9ec47480-039b-11e9-88c1-688633226347.JPG)

**Comment by rih28** [comment]
Cant seem to replicate at all.
