### ISSUE TITLE
Probability q7 crashed but in a weird way

### ISSUE THREAD

**Issue by ero24** [rih28/MBAndroidTest#25]
There were some crashes today when the app just quite unexpectedly but this was interesting because I accidentally tapped somewhere between the ‘back’ and the hint buttons (the little arrow in the bottom right corner of the Samsung device) and it quit the app (which is fair) but straigh after it came back without me pressing anything then it displayed the crash message (‘app quit unexpectedly ‘) so i closed it and reopened

**Comment by rih28** [comment]
Hopefully this kind of thing has been resolved since I plugged the memory leaks

**Comment by rih28** [comment]
Has this been resolved?

**Comment by ero24** [comment]
When I tried to recreate the issue just now I run into different problems: it correctly took me to the next little question but hitting the back button (the arrow in the corner of the device) took me to a blank 'little question page' or a 'get ready' page and it stayed there so I had to quit the app to continue

**Comment by rih28** [comment]
I think this is resolved. There was a downloading issue but also a weird anchor tag issue!
