### ISSUE TITLE
Geometry Q12

### ISSUE THREAD

**Issue by ero24** [rih28/MBAndroidTest#26]
I was on Q12, testing it at normal speed and when I answered the question (having already gone through all the little questions) and the museum came up I clicked continue and instead of going to the next question a blank white page came up with ‘Little Question ‘ at the top but otherwise it was completely empty. The app then took me to the ‘Get Ready’ page and i had to quit it to continue going through the questions

**Comment by rih28** [comment]
I think I fixed this.

**Comment by ero24** [comment]
it was fine now
