### ISSUE TITLE
‘Just initialising a few things...’

### ISSUE THREAD

**Issue by ero24** [rih28/MBAndroidTest#27]
I’m not sure if it was meant to come up but the app randomly took the me to this screen (I was on the main menu) and stayed there until I quit a few mins later

**Comment by rih28** [comment]
Ugh, strange logic with detecting internet changes no doubt. Hopefully resolved in this release.

**Comment by rih28** [comment]
Has this been resolved? I am not sure it has

**Comment by ero24** [comment]
it hasn't come up yet (and actually I haven't noticed it since I put up the issue
