### ISSUE TITLE
missing apostrophe in Q3 Algebra, first little question

### ISSUE THREAD

**Issue by ero24** [rih28/MBAndroidTest#3]
one of the answers to 'What is a sequence?' says 'a way of comparing two expressions that arent equal'

**Comment by rih28** [comment]
I am putting a new version out tonight, so you can try it again tomorrow.

**Comment by rih28** [comment]
I am putting a new version out tonight, so you can try it again tomorrow.

**Comment by ero24** [comment]
apostrophe is there now, it's fine
