### ISSUE TITLE
Probability Q4 hint 7 response to the first little question text slightly out of box

### ISSUE THREAD

**Issue by yw666666** [rih28/MBAndroidTest#31]
Jane basket question 
P(banana on 2nd try) the bracket was out of the box.
![wechat image_20190108100817](https://user-images.githubusercontent.com/42607534/50805469-8063f000-132d-11e9-9212-a24624689a00.jpg)

**Comment by rih28** [comment]
Should be fixed on tonights release

**Comment by yw666666** [comment]
not fixed for now
