### ISSUE TITLE
q12 geometry, the response box only came up halfway 

### ISSUE THREAD

**Issue by ero24** [rih28/MBAndroidTest#36]
![img_0374](https://user-images.githubusercontent.com/42607536/50845365-9214ba00-1364-11e9-99a2-40a25d244cdc.JPG)
a picture I took on my phone (hence the blurriness) when I answered the little question the response to the answer only came up about 2/3 of the screen

**Comment by rih28** [comment]
Hmm, thats annoying!. Good spot though.

**Comment by ero24** [comment]
it was actually Q11 and it worked fine now
