### ISSUE TITLE
the app crashed...

### ISSUE THREAD

**Issue by ero24** [rih28/MBAndroidTest#4]
I was on another question in Algebra when the app suddenly quit and a blank screen came up asking if I wanted to reopen so I clicked yes, and now it has been showing the 'Get Ready' page for a few minutes...
I'll try to trigger this again so I can see why this happened once it reopens

**Comment by rih28** [comment]
Has this mainly been solved?

**Comment by ero24** [comment]
it hasn't happened at all yesterday and today either
