### ISSUE TITLE
missing apostrophe in Q3 Ratio, hint 5, first little question

### ISSUE THREAD

**Issue by ero24** [rih28/MBAndroidTest#5]
in the 'note' section in bold it says 'students that didnt get an A' instead of didn't

**Comment by ero24** [comment]
and then the response to the answer (for the little question) also has a missing apostrophe

**Comment by ero24** [comment]
and the next little question as well, and the response to the last little question in hint8

**Comment by rih28** [comment]
Doh, I will need to fix this one later, it is not latex, I will need to construct another image.
