### ISSUE TITLE
Ratio Q4 glitching

### ISSUE THREAD

**Issue by ero24** [rih28/MBAndroidTest#6]
as I clicked on the second hint's reply it was about to come up (the green box on the black screen) but it stopped halfway through and started disappearing then coming back again, I then clicked elsewhere and it crashed 
I also made a video of it but Github doesn't seem to support that file..

**Comment by ero24** [comment]
happened again on q8 in ratio, I took a picture of the frozen screen this time:

![img_0107](https://user-images.githubusercontent.com/42607536/50095828-4318b080-020e-11e9-8ca3-527afb07a678.JPG)

**Comment by rih28** [comment]
Is this pretty much resolved now?

**Comment by rih28** [comment]
Is this pretty much resolved now?

**Comment by ero24** [comment]
q4 was fine, didn't experience any glitching
