### ISSUE TITLE
Screen stuck 

### ISSUE THREAD

**Issue by yw666666** [rih28/MBAndroidTest#8]
Sometimes when I tried to go to the second little question, the screen turned black and then white. (Both phones) Sometimes it was fine after waiting for a while, but this time it was stuck on this page. (Sony phone) Then I clicked on the arrow to go back and it goes to the “get ready” page and then was stuck.
![1391208e-160b-4355-87e9-a51932e3386b](https://user-images.githubusercontent.com/42607534/50091161-88a4a000-0245-11e9-9056-04c5a2042618.jpeg)

**Comment by yw666666** [comment]
The exact same thing happened again on Sony.

**Comment by yw666666** [comment]
Hmm this happened to huawei too. So basically it’s stuck on either the little question page or the get ready page.

**Comment by rih28** [comment]
Has this pretty much been resolved?

**Comment by yw666666** [comment]
Yes I feel that it seldom happens now.
