### ISSUE TITLE
Problems with going back from a little question 

### ISSUE THREAD

**Issue by yw666666** [rih28/MBAndroidTest#9]
When I encountered a hint with multiple little questions: After I did the first little question and was directed to the second one, I tried to go back from that page by clicking on the arrow at the top left corner. Sometimes it didn’t go back and just stayed on that page. I could see that the page refreshed itself, and the “another little question” at the top flashed too, suggesting that I did touch that arrow. This happened a few times on both phones.

**Comment by rih28** [comment]
Weird!

**Comment by rih28** [comment]
Has this pretty much been resolved?

**Comment by yw666666** [comment]
No it still happens in the newest version
